# Generated by Django 5.1.4 on 2024-12-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="class_type",
            field=models.CharField(
                choices=[("崇拜", "崇拜"), ("詩頌", "詩頌"), ("共習", "共習"), ("口風琴", "口風琴")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="class_type",
            field=models.CharField(
                choices=[("崇拜", "崇拜"), ("詩頌", "詩頌"), ("共習", "共習"), ("口風琴", "口風琴")],
                max_length=50,
            ),
        ),
    ]
