# Generated by Django 5.1.4 on 2024-12-12 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departments",
            new_name="Department",
        ),
        migrations.RenameModel(
            old_name="Roles",
            new_name="Role",
        ),
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
