# Generated by Django 5.1.4 on 2024-12-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="class_type",
            field=models.CharField(
                choices=[("Worship", "崇拜"), ("Hymn", "詩頌"), ("Extra Activity", "共習")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="class_type",
            field=models.CharField(
                choices=[("Worship", "崇拜"), ("Hymn", "詩頌"), ("Extra Activity", "共習")],
                max_length=50,
            ),
        ),
    ]
