# Generated by Django 5.1.4 on 2024-12-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="role",
        ),
        migrations.AddField(
            model_name="teacher",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.position",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
    ]
