# Generated by Django 5.1.4 on 2024-12-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_alter_teacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="class_type",
            field=models.CharField(
                choices=[("崇拜", "崇拜"), ("詩頌", "詩頌"), ("共習", "共習")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="class_type",
            field=models.CharField(
                choices=[("崇拜", "崇拜"), ("詩頌", "詩頌"), ("共習", "共習")], max_length=50
            ),
        ),
    ]
