# Generated by Django 5.1.4 on 2024-12-20 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_schedule_lesson_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="lesson_number",
            new_name="unit_number",
        ),
    ]
