# Generated by Django 5.1.4 on 2024-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_alter_activity_class_type_alter_schedule_class_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
