# Generated by Django 5.1.4 on 2024-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0006_alter_roleassignment_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("date", "department", "class_type"),
                name="unique_schedule_constraint",
            ),
        ),
    ]
