# Generated by Django 5.1.4 on 2024-12-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0007_schedule_unique_schedule_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="schedule.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="gender",
            field=models.CharField(choices=[("男", "男"), ("女", "女")], max_length=10),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[("擔任中", "擔任中"), ("休息中", "休息中"), ("新任", "新任")],
                default="Active",
                max_length=50,
            ),
        ),
    ]
