# Generated by Django 5.1.4 on 2024-12-15 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedule",
            "0008_alter_roleassignment_schedule_alter_teacher_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_role",
                to="schedule.classrole",
            ),
        ),
    ]
